apiVersion: v1
kind: Namespace
metadata:
  name: knative-upgrade

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: upgrade-check
  namespace: knative-upgrade

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upgrade-check-reader
rules:
- apiGroups:
  - eventing.knative.dev
  resources:
  - triggers
  verbs:
  - list
- apiGroups:
  - messaging.knative.dev
  resources:
  - subscriptions
  verbs:
  - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: upgrade-check-reader
subjects:
- kind: ServiceAccount
  name: upgrade-check
  namespace: knative-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: upgrade-check-reader

---

apiVersion: batch/v1
kind: Job
metadata:
  # generateName: upgrade-check-
  name: upgrade-check
  namespace: knative-upgrade
spec:
  template:
    metadata:
      labels:
        app: upgrade-check
    spec:
      serviceAccountName: upgrade-check
      restartPolicy: Never
      containers:
      - name: upgrade-check
        image: gcr.io/triggermesh/eventing-upgrade-check:v0.1.0

---

