apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upgrade-check-reader
rules:
- apiGroups:
  - eventing.knative.dev
  resources:
  - triggers
  verbs:
  - list
- apiGroups:
  - messaging.knative.dev
  resources:
  - subscriptions
  verbs:
  - get
